In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("hostel_choice.csv")
data.head()

,batch,gender,hostel,occupancy,Floors,Rooms,NumRoomsOnFloor,disabled
0,BTech22,male,Kalam A,Single,"0,1,2,3,4,5,6,7",(034 To 036) (100 To 117) (119 To 136) (200 To...,NaN,NaN
1,BTech22,male,Kalam B,Single,"1,2,3,4,5,6,7",(101 To 121) (201 To 221) (301 To 321) (401 To...,NaN,NaN
2,BTech23,male,Kalam C,Double,"1,2,3,4,5,6,7",(101 To 121) (201 To 221) (301 To 321) (401 To...,NaN,NaN
3,BTech23,male,Kalam D,Double,"0,1,2,3,4",(001 To 036) (101 To 136) (201 To 203) (205 To...,NaN,NaN
4,BTech24,male,Aryabhatta A,Double,"0,1,2,3,4,5,6,7",(003 To 028) (101 To 132) (201 To 232) (301 To...,NaN,NaN

In [3]:
data.columns

Index(['batch', 'gender', 'hostel', 'occupancy', 'Floors', 'Rooms',
       'NumRoomsOnFloor', 'disabled'],
      dtype='object')

In [4]:
available_rooms = {}
numRoomsAddedList = pd.DataFrame(columns = ["batch", "gender", "hostel","numRoomsAdded"]);
occupancy_map = { "Single": 1, "Double": 2, "Triple": 3 }
for i in range(data.shape[0]):
    numRoomsAdded = 0

    row = data.iloc[i]
    batch = row["batch"].strip().lower()
    hostel = row['hostel'].strip().lower()
    gender = row['gender'].strip().lower()


    if(batch not in available_rooms.keys()):
        available_rooms[batch] = {}
    if(gender not in available_rooms[batch].keys()):
        available_rooms[batch][gender] = {};
        available_rooms[batch][gender]["capacity"] = occupancy_map[row["occupancy"]]
        available_rooms[batch][gender]["hostels"] = {}
    available_rooms[batch][gender]["hostels"][hostel] = {};

    floors = [int(floor.strip()) for floor in row["Floors"].split(",")]
    for floor in floors:
        available_rooms[batch][gender]["hostels"][hostel][floor] = []
    rooms = row['Rooms'];
    if rooms != "All":
        rooms = rooms.replace(")", "");
        rooms = rooms.replace(" ", "");
        roomsFloor = rooms.split("(")[1:]
        for roomF in roomsFloor:
            roomsRange = roomF.split("To");
            floor = int(roomsRange[0][0]);
            for room in range(int(roomsRange[0][1:]), int(roomsRange[1][1:]) + 1):
                available_rooms[batch][gender]["hostels"][hostel][floor].append(room)
                numRoomsAdded += 1
    for floor in floors:
        # if floor is present but room data is not filled for that floor => all rooms in that floor
        if(not available_rooms[batch][gender]["hostels"][hostel][floor]):
            available_rooms[batch][gender]["hostels"][hostel][floor] = []
            for room in range(1, int(row['NumRoomsOnFloor'])+1):
        #        if((hostel in ['kalam a', 'kalam d'] and str(room).endswith('8')) or (row["hostel"].strip().lower() == 'kalam b' and floor == 1 and room in list(range(1,10)))):
        #            continue
                available_rooms[batch][gender]["hostels"][hostel][floor].append(room)
                numRoomsAdded += 1


    print(batch,gender, hostel, ":", numRoomsAdded, "Rooms Added", ":", "Occupancy", available_rooms[batch][gender]["capacity"])
    numRoomsAddedList.loc[len(numRoomsAddedList)] = [batch,gender,hostel, numRoomsAdded]

btech22 male kalam a : 255 Rooms Added : Occupancy 1
btech22 male kalam b : 147 Rooms Added : Occupancy 1
btech23 male kalam c : 147 Rooms Added : Occupancy 2
btech23 male kalam d : 130 Rooms Added : Occupancy 2
btech24 male aryabhatta a : 234 Rooms Added : Occupancy 2
btech24 male aryabhatta b : 74 Rooms Added : Occupancy 2
phd19 male kalam d : 8 Rooms Added : Occupancy 2
phd20 male kalam d : 20 Rooms Added : Occupancy 2
phd22 male aryabhatta b : 56 Rooms Added : Occupancy 1
btech23 female asima a : 3 Rooms Added : Occupancy 2
btech23 female asima c : 56 Rooms Added : Occupancy 2
btech23 female asima d : 5 Rooms Added : Occupancy 2
btech24 female asima d : 51 Rooms Added : Occupancy 3

In [5]:
available_rooms

{'btech22': {'male': {'capacity': 1,
   'hostels': {'kalam a': {0: [34, 35, 36],
     1: [0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36],
     2: [0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36],
     3: [0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36],
     4: [0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36],
     5: [0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36],
     6: [0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36],
     7: [0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36]},
    'kalam b': {1: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     2: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     3: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     4: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     5: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     6: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     7: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21]}}}},
 'btech23': {'male': {'capacity': 2,
   'hostels': {'kalam c': {1: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     2: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     3: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     4: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     5: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     6: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21],
     7: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21]},
    'kalam d': {0: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36],
     1: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36],
     2: [1,
      2,
      3,
      5,
      6,
      8,
      9,
      11,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      24,
      25,
      26,
      27,
      28,
      29,
      31,
      32,
      33,
      34,
      35,
      36],
     3: [1,
      2,
      3,
      4,
      7,
      8,
      10,
      11,
      14,
      15,
      16,
      18,
      19,
      20,
      22,
      23,
      25,
      26,
      27,
      28,
      30,
      31,
      32,
      33,
      35],
     4: [3, 5, 7, 8]}}},
  'female': {'capacity': 2,
   'hostels': {'asima a': {1: [3], 5: [5, 9]},
    'asima c': {0: [1, 2, 3, 4, 5, 6],
     1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     2: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     3: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     4: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     5: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
    'asima d': {0: [1, 2, 3, 4, 5]}}}},
 'btech24': {'male': {'capacity': 2,
   'hostels': {'aryabhatta a': {0: [3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28],
     1: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32],
     2: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32],
     3: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32],
     4: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32],
     5: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28],
     6: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28],
     7: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24]},
    'aryabhatta b': {0: [4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16],
     1: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32],
     2: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30]}}},
  'female': {'capacity': 3,
   'hostels': {'asima d': {0: [6],
     1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     2: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     3: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     4: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     5: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}}}},
 'phd19': {'male': {'capacity': 2,
   'hostels': {'kalam d': {5: [2, 3, 4, 5, 6, 8, 9, 10]}}}},
 'phd20': {'male': {'capacity': 2,
   'hostels': {'kalam d': {4: [12,
      13,
      14,
      15,
      17,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      32,
      33,
      34,
      35,
      36]}}}},
 'phd22': {'male': {'capacity': 1,
   'hostels': {'aryabhatta b': {2: [31, 32],
     3: [1,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32],
     4: [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25]}}}}}

In [6]:
import json
with open('available_rooms.json', 'w') as fp:
    json.dump(available_rooms, fp)

In [7]:
numRoomsAddedList

      batch  gender        hostel  numRoomsAdded
0   btech22    male       kalam a            255
1   btech22    male       kalam b            147
2   btech23    male       kalam c            147
3   btech23    male       kalam d            130
4   btech24    male  aryabhatta a            234
5   btech24    male  aryabhatta b             74
6     phd19    male       kalam d              8
7     phd20    male       kalam d             20
8     phd22    male  aryabhatta b             56
9   btech23  female       asima a              3
10  btech23  female       asima c             56
11  btech23  female       asima d              5
12  btech24  female       asima d             51

In [8]:
numRoomsAddedList.to_csv("numRoomsAdded.csv", index = False)